### ISSUE TITLE
Number of processes must be at least 1

### ISSUE THREAD

**Issue by PerisD** [yfukasawa/LongQC#3]
Hi Yoshinori,
Finally, I tried to use LongQC with a real data, but I got this error:
The command line
`MYPATH/conda_env/circlator/bin/python MYPATH/software/programs/LongQC/longQC.py sampleqc -x pb-rs2 -o longqc/ MYPATH/CompGenomics_Species/raw_reads/PacBio/TF100210M3/TF100210M3_1.fq -p 1
`
The error output:
`Traceback (most recent call last):
  File "MYPATH/software/programs/LongQC/longQC.py", line 919, in <module>
    main(args)`
 ` File "MYPATH/software/programs/LongQC/longQC.py", line 65, in main
    args.handler(args)`
 ` File "MYPATH/software/programs/LongQC/longQC.py", line 268, in command_sample
    lm = LqMask(os.path.join(path_minimap2, "sdust"), args.out, suffix=suffix, max_n_proc=10 if ncpu > 10 else ncpu)`
  `File "MYPATH/software/programs/LongQC/lq_mask.py", line 41, in __init__
    self.pool = mp.Pool(self.n_proc)`
 ` File "MYPATH/conda_env/circlator/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())`
 ` File "MYPATH/conda_env/circlator/lib/python3.6/multiprocessing/pool.py", line 168, in __init__
    raise ValueError("Number of processes must be at least 1")`
`ValueError: Number of processes must be at least 1`

Thanks,

Peris

**Comment by yfukasawa** [comment]
Dear @PerisD,

Sorry for late reply and inconvenience. I'll fix this issue.
In the meantime, could you please try some bigger number than 1 for -p?
like `-p 4`

Best,
Y

**Comment by PerisD** [comment]
Dear @yfukasawa,
With the next command using python3:
`python /cluster/projects/nn9699k/Speciomics/Peris/software/programs/LongQC/longQC.py sampleqc -x pb-rs2 -o longqc/StrainName_1 PacBioRead_1.fq -p 4`
LongQC works but once it reports the Mean GC composition sends an error.
`Traceback (most recent call last):
  File "/cluster/projects/nn9699k/Speciomics/Peris/software/programs/LongQC/longQC.py", line 919, in <module>
    main(args)
  File "/cluster/projects/nn9699k/Speciomics/Peris/software/programs/LongQC/longQC.py", line 65, in main
    args.handler(args)
  File "/cluster/projects/nn9699k/Speciomics/Peris/software/programs/LongQC/longQC.py", line 426, in command_sample
    gc_read_mean, gc_read_sd = lg.plot_unmasked_gc_frac(fp=fig_path_gc)
  File "/cluster/projects/nn9699k/Speciomics/Peris/software/programs/LongQC/lq_gcfrac.py", line 54, in plot_unmasked_gc_frac
    plt.hist(self.r_frac, alpha=0.3, bins=np.arange(min(self.r_frac), max(self.r_frac) + b_width, b_width), color='blue', normed=True)
  File "/cluster/projects/nn9699k/Speciomics/Peris/conda_env/circlator/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2610, in hist
    if data is not None else {}), **kwargs)
  File "/cluster/projects/nn9699k/Speciomics/Peris/conda_env/circlator/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/cluster/projects/nn9699k/Speciomics/Peris/conda_env/circlator/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6808, in hist
    p.update(kwargs)
  File "/cluster/projects/nn9699k/Speciomics/Peris/conda_env/circlator/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/cluster/projects/nn9699k/Speciomics/Peris/conda_env/circlator/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/cluster/projects/nn9699k/Speciomics/Peris/conda_env/circlator/lib/python3.6/site-packages/matplotlib/artist.py", line 1002, in _update_property
    .format(type(self).__name__, k))
AttributeError: 'Rectangle' object has no property 'normed'`
We are getting closer, thanks,
Peris

**Comment by yfukasawa** [comment]
Dear @PerisD,

Thank you for reporting the issue, and I've pushed some new codes to cope with newer one. (Sorry I'm still working on the first one).
Hopefully, this will resolve an issue.

Could you please download a new version of LongQC, and then try again?
Although I couldn't reproduce the same issue, I think this was caused by newer version of matplotlib. I've used and tested using an old one, ver 2.1.
Probably, in your environment, a newer matplotlib would have been used.

If you're ok, could you please share the version of your matplotlib?
To get the version, please type in your python:
`>>> import matplotlib`
`>>> matplotlib.__version__`
`'2.1.2'`

Thanks!

**Comment by astulaaa** [comment]
Hello @yfukasawa,

I started with the same error as @PerisD. After adding -p 4 it actually ran (got some stats) and got an error that looks like this:
longQC:2020-07-07 08:11:12,923:475:INFO:Genarated the sample read length plot.
longQC:2020-07-07 08:11:12,923:477:INFO:Throughput: 737228
longQC:2020-07-07 08:11:12,923:478:INFO:Length of longest read: 25168
longQC:2020-07-07 08:11:12,923:479:INFO:The number of reads: 121
longQC:2020-07-07 08:11:12,924:508:INFO:Process 450 for /home/user/LongQC/minimap2_mod/minimap2-coverage terminated.
longQC:2020-07-07 08:11:12,924:512:INFO:Overlap computation finished.
longQC:2020-07-07 08:11:22,933:584:INFO:Generating coverage related plots...
lq_coverage:2020-07-07 08:11:22,938:120:INFO:Estimating coverage distribution..
/opt/conda/lib/python3.7/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)
Traceback (most recent call last):
  File "longQC.py", line 932, in <module>
    main(args)
  File "longQC.py", line 62, in main
    args.handler(args)
  File "longQC.py", line 588, in command_sample
    lc = LqCoverage(cov_path, isTranscript=args.transcript, control_filtering=pb_control)
  File "/home/user/LongQC/lq_coverage.py", line 121, in __init__
    self.__est_coverage()
  File "/home/user/LongQC/lq_coverage.py", line 220, in __est_coverage
    model_main_comp = self.__est_coverage_dist_gmm(k_i=2)
  File "/home/user/LongQC/lq_coverage.py", line 546, in __est_coverage_dist_gmm
    m_f   = mixture.GaussianMixture(n_components=k).fit(nonzeros[nonzeros < th_per].reshape(-1,1),1)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 220, in fit_predict
    X = _check_X(X, self.n_components, ensure_min_samples=2)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 53, in _check_X
    ensure_min_samples=ensure_min_samples)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 2 is required.


What went wrong and how can I fix it?
Thanks
Asta

**Comment by yfukasawa** [comment]
Dear @astulaaa,

Sorry for late response and inconinience.
I think that you hit a rare case where data set has extremely low coverage. Please let me follow your case in issue #11.
Coincidently, I faced the same error last week in a failed run case, so soon I'll upload a minor update.

Best,
Y.

**Comment by HeQSun** [comment]
> Dear @astulaaa,
> 
> Sorry for late response and inconinience. I think that you hit a rare case where data set has extremely low coverage. Please let me follow your case in issue #11. Coincidently, I faced the same error last week in a failed run case, so soon I'll upload a minor update.
> 
> Best, Y.

Hi @yfukasawa ,

have you updated the tool as you proposed above? I am still facing the same error "minimap2-coverage terminated".

I do have a low coverage (HiFi reads), around 15x (and some regions could be around 3x).  

Is there an elegant way to avoid this error and let the program finish properly?

thanks,
Hequan
